### ISSUE TITLE
Latest Todo:

### ISSUE THREAD

**Issue by zverofaust** [SpringMCLegacy/SpringMCLegacy#115]
- [x] Add Track/Wheel damage for vehicles, just like legs for Mechs. Use trackr/trackl and/or wheel# for hitboxes.
- [x] Hovercraft Pad
- [x] 4 tiers for Vehicles and 3 for Hovercraft.
- [x] Way to separate the tiers (light/med/heavy&superheavy/house) but allow exceptions, namely Goblin Transport medium apc carrying over to heavy (and then being replaced by house)
- [x] Come up with a solution for LBXs, or decision to not have a solution. They should fire regular AC ammo at regular AC ranges, switching to grapeshot only up close.
- [ ] Use that same solution for MMLs, which can fire both SRMs and LRMs.
- [x] Finalize plan for VTOLs. A VTOL bay? Vpads chug them out occasionally? There aren't really enough VTOLs to justify their own pad. Currently I have 3 universal VTOLs, which factions getting House replacements for some (not nearly all).

**Comment by FLOZi** [comment]
LBX's done! I still have the track/wheel damage halfway done on my local, too.

**Comment by FLOZi** [comment]
Removed MORE PERKS (#105) and Accuracy (#116) as they have their own issues

**Comment by zverofaust** [comment]
No we don't really need MMLs right now. They can just be LRMs or whatever. It's an interesting gimmick tho and we should do it at some point.

**Comment by FLOZi** [comment]
Decided not to pursue MMLs, at least for now. My view is that under current sides & unittables they only really appear on a couple of tanks (which are arguably out of timeline anyway) and not mechs.
