### ISSUE TITLE
Unimplemented Mods

### ISSUE THREAD

**Issue by FLOZi** [SpringMCLegacy/SpringMCLegacy#152]
Firstly 
- [x] Incompatibility is not implemented
- [x] Pre-installed mods are not implemented

Then there are several mods missing at current:
- [x] Supercharger (requires Run command)
- [x] ~~CASE (requires that units take additional damage when weapon arms are blown off)~~
- [x] Stealth armour (requires that stealth armour be implemented cf #123 
- [x] Anti-Aircraft Targeting Computer (requires either AllowUnitTarget or BlockShot manipulation of weapons on a per-target basis)
- [x] Artemis LRM (requires that Artemis be implemented cf #141 )
- [x] Artemis SRM (requires that Artemis be implemented cf #141 )
- [x] Arrow Homing Missile (requires that TAG homing be implemented)
- [x] ~~3x iNarc pods (pending decision on iNarc itself)~~
- [x] LRM ARAD (Requires an exception in ECM targetting for jammers themselves only)
- [x] LRM Semi-Guided Warheads/Smart Warheads (requires TAG homing be implemented)

**Comment by zverofaust** [comment]
- Supercharger still requires some kind of limiting mechanic like MASC but different. MASC generates heat and damages legs, what will Superchargers do?
- CASE and limb destruction damage is low priority for me. In fact limb destruction damage is almost entirely just a justification for CASE as a mod.
- Stealth Armour <3
- Artemis system and Extended Range LRM should be exclusive to ammo I think.
- Homing Arrow plsssssss.
- Yeah fuck iNarc they can wait for if/when Comstar is ever a thing.
- ARAD seems like a cool thing but low priority?
- Smart LRM might as well do it when doing Arrow.

**Comment by FLOZi** [comment]
If we are leaving CASE and iNARC for now, then we're done! Wiki needs some updating with the tweaks made along the way.
